Models/SheetDetailsCalculation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Finance.Models
{
    public class SheetDetailsCalculation
    {
        public int Id { get; set; }
        [Required]
        public string InvoiceNumber { get; set; }
        [Required]
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public DateTime InvoiceDate { get; set; }
        [Required]
        public double MaterialPrice { get; set; } //Сумма без НДС за метериал из счета поставщика
        [Required]
        public double CuttingPrice { get; set; } // Сумма без НДС за порезку из счета поставщика
        [Required]
        public double Area { get; set; } // площадь листа в м.кв. из которого будут вырезаться заготовки
        [Required]
        public int SheetThickness { get; set; }
        public double WasteCoeficcient { get; set; }  // коэфициент отхода, расчтывется для каждого случая отдельно
        [Required]
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public DateTime CalculationDate { get; set; }
        public double[] DetailsSquares { get; set; } // // Площадь деталей. Нужна для вычисления коэф.отхода - sheetDetailsCalculation.WasteCoeficcient 
        public double[] ItemsPercentages { get; set; } // доля каждой детали от площади листа в %

        public double PriceFluctuationCoefficient { get; set; } // коэффициент колебания цены, закладывается в стоимость изделия

        public virtual ICollection<DetailCalculation> DetailsCalculation { get; set; }
    }
}

Controllers/SheetDetailsCalculationController.cs
using Finance.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Finance.Controllers
{
    public class SheetDetailsCalculationController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: SheetDetailsCalculations
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Calculation(SheetDetailsCalculation sheetDetailsCalculation, SheetDetailViewModels sheetDetailViewModels)
        {
            DetailCalculation[] Details = Calculate(sheetDetailsCalculation, sheetDetailViewModels);

            //sheetDetailsCalculation.DetailsCalculation.details = details;
            DetailsPricesAndWasteCoef detailsPricesAndWasteCoef = new DetailsPricesAndWasteCoef();
            detailsPricesAndWasteCoef.DetailsPrices = Details.Select(i => i.DetailPrice).ToArray();
            detailsPricesAndWasteCoef.WasteCoef = sheetDetailsCalculation.WasteCoeficcient;

            //return Json(res);
            return Json(detailsPricesAndWasteCoef);
        }

        private static DetailCalculation[] Calculate(SheetDetailsCalculation sheetDetailsCalculation, SheetDetailViewModels sheetDetailViewModels)
        {
            DetailCalculation[] Details = new DetailCalculation[sheetDetailViewModels.DetailNumber.Length];

            sheetDetailsCalculation.DetailsSquares = new double[sheetDetailViewModels.DetailNumber.Length];
            for (int i = 0; i < sheetDetailViewModels.DetailNumber.Length; i++)
            {
                sheetDetailsCalculation.DetailsSquares[i] = (sheetDetailViewModels.DetailAmount[i] * sheetDetailViewModels.DetailLength[i] * sheetDetailViewModels.DetailWidth[i]) / 1000000;
            }
            // Рассчитываем коэф.отхода по всему заказу
            sheetDetailsCalculation.WasteCoeficcient = sheetDetailsCalculation.Area / sheetDetailsCalculation.DetailsSquares.Sum();

            // доля каждой детали от площади листа в %
            //decimal[] ItemsPercentages = new decimal[sheetDetailViewModels.DetailNumber.Length];
            sheetDetailsCalculation.ItemsPercentages = new double[sheetDetailViewModels.DetailNumber.Length];

            for (int i = 0; i < sheetDetailViewModels.DetailNumber.Length; i++)
            {
                sheetDetailsCalculation.ItemsPercentages[i] = (sheetDetailsCalculation.DetailsSquares[i] * sheetDetailsCalculation.WasteCoeficcient) / sheetDetailsCalculation.Area;
                // считаем стоимость за материалл для каждой детали

                Details[i] = new DetailCalculation();
                Details[i].MaterialPrice = sheetDetailsCalculation.MaterialPrice * sheetDetailsCalculation.ItemsPercentages[i];
                // считаем стоимость работы для каждой детали
                Details[i].WorkPrice = sheetDetailsCalculation.CuttingPrice * sheetDetailsCalculation.ItemsPercentages[i];
                // считаем стоимость каждой детали
                Details[i].DetailPrice = (Details[i].MaterialPrice + Details[i].WorkPrice) / sheetDetailViewModels.DetailAmount[i];
            }

            return Details;
        }

        [HttpPost]
        public ActionResult SaveCalculation(SheetDetailsCalculation sheetDetailsCalculation, SheetDetailViewModels sheetDetailViewModels/*, int? detId*/)
        {
            SheetDetail[] details = new SheetDetail[sheetDetailViewModels.DetailNumber.Length];
            for (int j = 0; j < details.Length; j++)
            {
                if(sheetDetailViewModels.DetailId[j] == -1)
                {
                    details[j] = new SheetDetail();
                    details[j].DetailLength = sheetDetailViewModels.DetailLength[j];
                    details[j].DetailName = sheetDetailViewModels.DetailName[j];
                    details[j].DetailNumber = sheetDetailViewModels.DetailNumber[j];
                    details[j].DetailWidth = sheetDetailViewModels.DetailWidth[j];
                    details[j].DetailThickness = sheetDetailsCalculation.SheetThickness;
                    db.SheetDetails.Add(details[j]);
                }
                else
                {
                    details[j] = db.SheetDetails.Find(sheetDetailViewModels.DetailId[j]);
                }

                DetailCalculation detailCalculation = new DetailCalculation();
                detailCalculation.Calculation = sheetDetailsCalculation;
                detailCalculation.Detail = details[j]; 
                detailCalculation.Amount = sheetDetailViewModels.DetailAmount[j];
                detailCalculation.DetailsSquare = detailCalculation.Amount * details[j].DetailLength * details[j].DetailWidth;
                detailCalculation.DetailPrice = sheetDetailViewModels.DetailPrice[j];

                db.DetailsCalculations.Add(detailCalculation);
            }

            db.SheetDetailsCalculations.Add(sheetDetailsCalculation);
            db.SaveChanges();

            return RedirectToAction("GetAllCalculations", db.SheetDetailsCalculations.ToList());
        }

        public ActionResult GetAllCalculations()
        {
            return View(db.SheetDetailsCalculations.ToList());
        }

        public ActionResult GetAllDetails()
        {
            var det = db.SheetDetails.ToList();
            return View(db.SheetDetails.ToList());
        }

        [HttpGet]
        public ActionResult EditCalculation(int id)
        {
            var editedCalc = db.SheetDetailsCalculations.Find(id);
            return View(db.SheetDetailsCalculations.Find(id));
        }

        [HttpPost]
        public async System.Threading.Tasks.Task<ActionResult> EditCalculation(SheetDetailsCalculation Calculation, SheetDetailViewModels sheetDetailViewModels /*int[] DetailId*/)
        {
            if (ModelState.IsValid)
            {
                SheetDetailsCalculation currentCalculation = await db.SheetDetailsCalculations.FindAsync(Calculation.Id);
                currentCalculation.Area = Calculation.Area;
                currentCalculation.CalculationDate = Calculation.CalculationDate;
                currentCalculation.CuttingPrice = Calculation.CuttingPrice;
                currentCalculation.DetailsSquares = Calculation.DetailsSquares;
                currentCalculation.InvoiceDate = Calculation.InvoiceDate;
                currentCalculation.InvoiceNumber = Calculation.InvoiceNumber;
                currentCalculation.ItemsPercentages = Calculation.ItemsPercentages;
                currentCalculation.MaterialPrice = Calculation.MaterialPrice;
                currentCalculation.SheetThickness = Calculation.SheetThickness;
                currentCalculation.WasteCoeficcient = Calculation.WasteCoeficcient;

                currentCalculation.DetailsCalculation.Clear();

                for(var i = 0; i < sheetDetailViewModels.DetailId.Length; i++)
                {
                    DetailCalculation detailCalculation = new DetailCalculation();
                    currentCalculation.DetailsCalculation.Add(detailCalculation);
                    if (sheetDetailViewModels.DetailId[i] != -1)
                    {
                        detailCalculation.Detail = db.SheetDetails.Find(sheetDetailViewModels.DetailId[i]);
                    }
                    else
                    {
                        SheetDetail newDetail = new SheetDetail();
                        newDetail.DetailLength = sheetDetailViewModels.DetailLength[i];
                        newDetail.DetailName = sheetDetailViewModels.DetailName[i];
                        newDetail.DetailNumber = sheetDetailViewModels.DetailNumber[i];
                        newDetail.DetailThickness = currentCalculation.SheetThickness;
                        newDetail.DetailWidth = sheetDetailViewModels.DetailWidth[i];
                        db.SheetDetails.Add(newDetail);
                        detailCalculation.Detail = newDetail;
                    }
                    detailCalculation.Amount = sheetDetailViewModels.DetailAmount[i]; ;
                    detailCalculation.DetailsSquare = (sheetDetailViewModels.DetailAmount[i] * sheetDetailViewModels.DetailLength[i] * sheetDetailViewModels.DetailWidth[i]) / 1000000;
                    detailCalculation.DetailPrice = sheetDetailViewModels.DetailPrice[i];
                }


                await db.SaveChangesAsync();

            }
            return RedirectToAction("GetAllCalculations");
        }

        class DetailInfo
        {
            public int ID { get; set; }
            public string DetailName { get; set; }
            public double DetailLength { get; set; }
            public double DetailWidth { get; set; }
        }

        [HttpGet]
        public JsonResult GetDetailsByName(string detailNameValue)
        {
            List<SheetDetail> DetailsList = db.SheetDetails.Where(n => n.DetailName.Contains(detailNameValue)).ToList();
            List<DetailInfo> DetailsInfo = new List<DetailInfo>();
            foreach (var i in DetailsList)
            {
                DetailInfo Detail = new DetailInfo();
                Detail.ID = i.Id;
                Detail.DetailName = i.DetailName;
                Detail.DetailLength = i.DetailLength;
                Detail.DetailWidth = i.DetailWidth;
                DetailsInfo.Add(Detail);
            }            
            return Json(DetailsInfo, JsonRequestBehavior.AllowGet);
        }

        //[HttpPost]
        public ActionResult Delete(int id)
        {
            //Для удаления калькуляции необходимо вначале удалить все связи с деталями (detailCalculations)
            
            SheetDetailsCalculation calculation = db.SheetDetailsCalculations.Find(id);
            List<DetailCalculation> detailCalculations = calculation.DetailsCalculation.ToList();

Views/SheetDetailsCalculation/GetAllCalculations.cshtml
@model IEnumerable<Finance.Models.SheetDetailsCalculation>
<link href="~/CSS/getAllCalculations.css" rel="stylesheet" />
@{
    ViewBag.Title = "GetAllCalculations";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Все расчеты</h2>
<input type="button" value="Все детали" onclick="location.href='@Url.Action("GetAllDetails", "SheetDetailsCalculation")'" />
<p>
    @Html.ActionLink("Создать новый", "Index")
</p>
<table class="table">
    <tr>
        <th>
            Номер счета
        </th>
        <th>
            Дата расчета
        </th>
        <th>
            Стоимость матер.без НДС
        </th>
        <th>
            Стоимость порезки без НДС
        </th>
        <th>
            Площадь листа
        </th>
        <th>
            Толщина листа
        </th>
        <th>
            Коэф.отхода
        </th>
        <th>
            Дата расчета
        </th>
        <th style="text-align:center"> Действия </th>
    </tr>

    @{
        int counter = 0;
        string className;
    }
    @foreach (var item in Model)
    {
        counter++;
        className = (counter % 2 == 0 ? "back_color_even" : "back_color_odd");
        <tr style = "cursor: pointer; border: 2px solid black"  class=@className>
            @*<td>@className</td>*@
            <td>
                @Html.DisplayFor(modelItem => item.InvoiceNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InvoiceDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaterialPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CuttingPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Area)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SheetThickness)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WasteCoeficcient)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CalculationDate)
            </td>
            <td>
                @Html.ActionLink("Редактировать", "EditCalculation", new { id = item.Id }) |
                @{string showHideDetailsLinkName = "showHideDetailsLinkName" + item.Id; }
                <a name="@showHideDetailsLinkName" onclick="showDetails(id = @item.Id, event);" style="cursor: pointer">Просмотреть</a>
                @*@Html.ActionLink("Просмотреть", "Details", new { onclick = "showDetails(id = item.Id);" })*@ |
                @Html.ActionLink("Удалить", "Delete", new { id = item.Id })
            </td>
        </tr>
        <tr style="border: hidden" name="@item.Id" hidden>
            <th scope="col">#</th>
            <th scope="col"> Деталь </th>
            <th scope="col"> Длинна </th>
            <th scope="col"> Ширина </th>
            <th scope="col"> Кол-во </th>
            <th scope="col"> Цена (без НДС) </th>
            <th></th>
            <th></th>
            <th></th>
        </tr>
        int detailNumber = 0;
        foreach (var i in item.DetailsCalculation)
        {
            detailNumber++;
            <tr name="@item.Id" hidden>
                <th scope="row">@detailNumber</th>
                <td>@i.Detail.DetailName</td>
                <td>@i.Detail.DetailLength</td>
                <td>@i.Detail.DetailWidth</td>
                <td>@i.Amount</td>
                <td>@i.DetailPrice</td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        }
    }
</table>
<script>
    //console.log($(".back_color").length);
    //for (let i = 0; i < ($(".back_color").length); i+=2) {
    //    var evenElement = $(".back_color")[i];
    //    var oddElement = $(".back_color")[i+1];
    //    $(evenElement).class(".back_color_even");
    //    $(oddElement).addClass(".back_color_odd");
    //}
    //for (let j = 1; j < ($(".back_color").length); i += 2) {
    //    var currentElement = $(".back_color")[j];
    //    $(".back_color")[j].addClass(".back_color_odd");
    //}

    function showDetails(id, event) {
        var hiddenTrCollection = $("tr[name=" + id + "]");
        console.log(hiddenTrCollection);
        var showHideDetailsLinkCollection = $("a[name=showHideDetailsLinkName" + id + "]");

        if (showHideDetailsLinkCollection[0].innerHTML === "Просмотреть") {
            hiddenTrCollection.each(function () {
                $(this).show();
                var parentElemBackgroundColor = $(event.target).parent().parent().css("background-color");
                $(this).css("background-color", parentElemBackgroundColor);
                $(this).css("border", "1px solid black");
            });
            showHideDetailsLinkCollection[0].innerHTML = "Скрыть";
        } else {
            $("tr[name=" + id + "]").each(function () {
                $(this).hide();
            })
            showHideDetailsLinkCollection[0].innerHTML = "Просмотреть";
        }

    }

    function showDetailsClickByRow(id, event) {
        //var showHideLink = $(event.target).parent().children().last().children()[1];
        //if (showHideLink.innerHTML === "Просмотреть") {
        //    $("tr[name=" + id + "]").each(function () {
        //        $(this).show();
        //        var parentElemBackgroundColor = $(event.target).parent().parent().css("background-color");
        //        $(this).css("background-color", parentElemBackgroundColor);
        //        $(this).css("border", "1px solid black");
        //    });
        //    showHideLink.innerHTML = "Скрыть";
        //}
        //else {
        //    $("tr[name=" + id + "]").each(function () {
        //        $(this).hide();
        //    });
        //    showHideLink.innerHTML = "Просмотреть";
        //}
    }
</script>

Views/SheetDetailsCalculation/GetAllDetails.cshtml
@model IEnumerable<Finance.Models.SheetDetail>

@{
    ViewBag.Title = "GetAllDetailsPrices";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    tr:nth-child(2n+1){
        background-color: aliceblue;
    }
    .rows:hover {
        cursor: pointer;
        background-color: #ccc;
    }
</style>
<h2>Справочник деталей</h2>

<input type="button" value="Все расcчеты" onclick="location.href='@Url.Action("GetAllCalculations", "SheetDetailsCalculation")'" />
<p>
    @Html.ActionLink("Создать новый", "Index")
</p>
<table class="table">
    <tr>
        @*<th>
                @Html.DisplayNameFor(model => model.DetailNumber)
            </th>*@
        <th>
            Деталь
        </th>
        <th>
            Длинна, мм
        </th>
        <th>
            Ширина, мм
        </th>
        <th>
            Толшина, мм
        </th>
        <th>
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr class="rows" onclick="location.href='@Url.Action("GetDetailCalculationIfo", "SheetDetailsCalculation", new {detailId = item.Id})'">
            @*<td>
                    @Html.DisplayFor(modelItem => item.DetailNumber)
                </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.DetailName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DetailLength)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DetailWidth)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DetailThickness)
            </td>
            <td>
                @Html.ActionLink("Редактировать", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Просмотреть", "Details", new { id = item.Id }) |
                @Html.ActionLink("Удалить", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

Views/SheetDetailsCalculation/GetDetailCalculationIfo.cshtml
@model List<Finance.Models.DetailCalculation>

@{
    ViewBag.Title = "GetDetailCalculationIfo";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .inline {
        display: inline-block;
        margin: 10px;
    }
    .text_to_right{
        align-content: right;
    }
</style>

<h2>Движение по детали: @ViewBag.DetailName (@Model[0].Detail.DetailLength * @Model[0].Detail.DetailWidth * @Model[0].Calculation.SheetThickness мм.)</h2>

<input type="button" value="Все расcчеты" onclick="location.href='@Url.Action("GetAllCalculations", "SheetDetailsCalculation")'" />
<input type="button" value="Все детали" onclick="location.href='@Url.Action("GetAllDetails", "SheetDetailsCalculation")'" />
<p>
    @Html.ActionLink("Создать новый", "Index")
</p>
<div>
    <div class="inline">
        Минимальная цена детали -
    </div>
    <div class="inline text_to_right">
        @ViewBag.MinPrice грн.
    </div>
</div>

<div>
    <div class="inline">
        Максимальная цена детали -
    </div>
    <div class="inline text_to_right">
        @ViewBag.MaxPrice грн.
    </div>
</div>

<div>
    <div class="inline">
        Средняя цена детали -
    </div>
    <div class="inline text_to_right">
        @ViewBag.AvarageDetailPrice грн.
    </div>
</div>


<table class="table">
    <tr>
        <th>
            № Счета поставщика
        </th>
        <th>
            Дата счета
        </th>
        <th>
            Кол-во шт.
        </th>
        <th>
            Цена грн.
        </th>
        <th>
            Коэф.отхода
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Calculation.InvoiceNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Calculation.InvoiceDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DetailPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Calculation.WasteCoeficcient)
            </td>
            @*<td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>*@
        </tr>
    }

</table>

Views/SheetDetailsCalculation/SaveCalculation.cshtml
@model Finance.Models.SheetDetailsCalculation

@{
    ViewBag.Title = "CalculationResults";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Рассчет №@Model.Id успешно сохранен</h2>
@Html.DisplayName("Дата расчета ")@Model.CalculationDate.ToString("MM/dd/yyyy")

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Номер счета")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InvoiceNumber)
        </dd>

        <dt>
            @Html.DisplayName("Дата счета")
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.InvoiceDate)*@
            @Model.InvoiceDate.ToString("MM/dd/yyyy")
        </dd>
        <br />
        <dt>
            @Html.DisplayName("Стоимость метериала")
        </dt>

        <dd>
            @{ var materialPriceAsDouble = string.Format("{0:0.00}", Model.MaterialPrice); }
            @Html.DisplayFor(model => materialPriceAsDouble) грн.
        </dd>

        <dt>
            @Html.DisplayName("Стоимость порезки")
        </dt>

        <dd>
            @{ var workPriceAsDouble = string.Format("{0:0.00}", Model.CuttingPrice); }
            @Html.DisplayFor(model => workPriceAsDouble) грн.
        </dd>

        <dt>
            @Html.DisplayName("Площадь листа")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Area) м.кв.
        </dd>

        <dt>
            @Html.DisplayName("Толщина листа")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SheetThickness) мм.
        </dd>
        <br />
        <dt>
            @Html.DisplayName("Коэфициент отхода")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WasteCoeficcient)
        </dd>

        @*<dt>
                @Html.DisplayName("Дата расчета")
            </dt>*@

        @*<dd>
                @Model.CalculationDate.ToString("MM/dd/yyyy")
                @Html.DisplayFor(model => model.CalculationDate)
            </dd>*@
        <br />
    </dl>
</div>

<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col"> Название детали </th>
            <th scope="col"> Длинна </th>
            <th scope="col"> Ширина </th>
            <th scope="col"> Кол-во </th>
            <th scope="col"> Цена (без НДС) </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var i in Model.Details)
        {
            <tr>
                <th scope="row">@i.DetailNumber</th>
                <td>@i.DetailName</td>
                <td>@i.DetailLength</td>
                <td>@i.DetailWidth</td>
                <td>@i.DetailAmount</td>
                <td>@i.DetailPrice</td>
            </tr>
        }
    </tbody>
</table>

<p>
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Назад", "Index")
</p>